/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrganizerRouteImport } from './routes/organizer'
import { Route as BuyerRouteImport } from './routes/buyer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as EventsIdSeatsRouteImport } from './routes/events.$id.seats'

const OrganizerRoute = OrganizerRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerRoute = BuyerRouteImport.update({
  id: '/buyer',
  path: '/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdSeatsRoute = EventsIdSeatsRouteImport.update({
  id: '/seats',
  path: '/seats',
  getParentRoute: () => EventsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/buyer': typeof BuyerRoute
  '/organizer': typeof OrganizerRoute
  '/events/$id': typeof EventsIdRouteWithChildren
  '/events/$id/seats': typeof EventsIdSeatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/buyer': typeof BuyerRoute
  '/organizer': typeof OrganizerRoute
  '/events/$id': typeof EventsIdRouteWithChildren
  '/events/$id/seats': typeof EventsIdSeatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/buyer': typeof BuyerRoute
  '/organizer': typeof OrganizerRoute
  '/events/$id': typeof EventsIdRouteWithChildren
  '/events/$id/seats': typeof EventsIdSeatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/buyer'
    | '/organizer'
    | '/events/$id'
    | '/events/$id/seats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/buyer'
    | '/organizer'
    | '/events/$id'
    | '/events/$id/seats'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/buyer'
    | '/organizer'
    | '/events/$id'
    | '/events/$id/seats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BuyerRoute: typeof BuyerRoute
  OrganizerRoute: typeof OrganizerRoute
  EventsIdRoute: typeof EventsIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/organizer': {
      id: '/organizer'
      path: '/organizer'
      fullPath: '/organizer'
      preLoaderRoute: typeof OrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer': {
      id: '/buyer'
      path: '/buyer'
      fullPath: '/buyer'
      preLoaderRoute: typeof BuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id/seats': {
      id: '/events/$id/seats'
      path: '/seats'
      fullPath: '/events/$id/seats'
      preLoaderRoute: typeof EventsIdSeatsRouteImport
      parentRoute: typeof EventsIdRoute
    }
  }
}

interface EventsIdRouteChildren {
  EventsIdSeatsRoute: typeof EventsIdSeatsRoute
}

const EventsIdRouteChildren: EventsIdRouteChildren = {
  EventsIdSeatsRoute: EventsIdSeatsRoute,
}

const EventsIdRouteWithChildren = EventsIdRoute._addFileChildren(
  EventsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BuyerRoute: BuyerRoute,
  OrganizerRoute: OrganizerRoute,
  EventsIdRoute: EventsIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
